# Generated by Django 3.1.1 on 2020-10-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firstSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'Computer Science Engineering'), ('ISE', 'Information Science Engineering'), ('ECE', 'Electronic Engineering'), ('ME', 'Mechanical Engineering'), ('CVE', 'Civil Engineering'), ('AI & ML', 'Artificial Intelligence and Machine Learning.'), ('TCE', 'Telecommunications Engineering'), ('EEE', 'Electrical and Electronics Engineering')], max_length=10)),
                ('section', models.CharField(blank=True, choices=[('A', 'A Section'), ('B', 'B Section'), ('C', 'C Section')], max_length=1)),
                ('images', models.FileField(blank=True, max_length=1, upload_to=(('A', 'A_section'), ('B', 'B_section'), ('C', 'C_section')))),
            ],
        ),
    ]
