# Generated by Django 3.1.1 on 2020-10-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstsemester',
            name='UPLOAD',
            field=models.CharField(blank=True, choices=[('A', 'A Section'), ('B', 'B Section'), ('C', 'B Section')], max_length=10),
        ),
        migrations.AlterField(
            model_name='firstsemester',
            name='images',
            field=models.FileField(blank=True, max_length=50, upload_to=models.CharField(blank=True, choices=[('A', 'A Section'), ('B', 'B Section'), ('C', 'B Section')], max_length=10)),
        ),
    ]
