# Generated by Django 3.1.1 on 2020-10-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0003_auto_20201029_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstsemester',
            name='usn',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
