# Generated by Django 3.1.1 on 2020-10-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0004_firstsemester_usn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstsemester',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ISE', 'Information Science Engineering'), ('ECE', 'Electronic Engineering'), ('ME', 'Mechanical Engineering'), ('CVE', 'Civil Engineering'), ('AI & ML', 'Artificial Intelligence and Machine Learning.'), ('TCE', 'Telecommunications Engineering'), ('EEE', 'Electrical and Electronics Engineering')], max_length=10),
        ),
        migrations.AlterField(
            model_name='firstsemester',
            name='images',
            field=models.FileField(max_length=50, upload_to='firstYear'),
        ),
        migrations.AlterField(
            model_name='firstsemester',
            name='section',
            field=models.CharField(choices=[('A', 'A Section'), ('B', 'B Section'), ('C', 'C Section')], max_length=1),
        ),
        migrations.AlterField(
            model_name='firstsemester',
            name='usn',
            field=models.CharField(max_length=10),
        ),
    ]
