# Generated by Django 3.1.1 on 2020-10-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0005_auto_20201029_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usn', models.CharField(max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ISE', 'Information Science Engineering'), ('ECE', 'Electronic Engineering'), ('ME', 'Mechanical Engineering'), ('CVE', 'Civil Engineering'), ('AI & ML', 'Artificial Intelligence and Machine Learning.'), ('TCE', 'Telecommunications Engineering'), ('EEE', 'Electrical and Electronics Engineering')], max_length=10)),
                ('section', models.CharField(choices=[('A', 'A Section'), ('B', 'B Section'), ('C', 'C Section')], max_length=1)),
                ('images', models.FileField(max_length=50, upload_to='FirstYear')),
            ],
        ),
        migrations.CreateModel(
            name='FourthYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usn', models.CharField(max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ISE', 'Information Science Engineering'), ('ECE', 'Electronic Engineering'), ('ME', 'Mechanical Engineering'), ('CVE', 'Civil Engineering'), ('AI & ML', 'Artificial Intelligence and Machine Learning.'), ('TCE', 'Telecommunications Engineering'), ('EEE', 'Electrical and Electronics Engineering')], max_length=10)),
                ('section', models.CharField(choices=[('A', 'A Section'), ('B', 'B Section'), ('C', 'C Section')], max_length=1)),
                ('images', models.FileField(max_length=50, upload_to='FourthYear')),
            ],
        ),
        migrations.CreateModel(
            name='SecondYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usn', models.CharField(max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ISE', 'Information Science Engineering'), ('ECE', 'Electronic Engineering'), ('ME', 'Mechanical Engineering'), ('CVE', 'Civil Engineering'), ('AI & ML', 'Artificial Intelligence and Machine Learning.'), ('TCE', 'Telecommunications Engineering'), ('EEE', 'Electrical and Electronics Engineering')], max_length=10)),
                ('section', models.CharField(choices=[('A', 'A Section'), ('B', 'B Section'), ('C', 'C Section')], max_length=1)),
                ('images', models.FileField(max_length=50, upload_to='SecondYear')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usn', models.CharField(max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ISE', 'Information Science Engineering'), ('ECE', 'Electronic Engineering'), ('ME', 'Mechanical Engineering'), ('CVE', 'Civil Engineering'), ('AI & ML', 'Artificial Intelligence and Machine Learning.'), ('TCE', 'Telecommunications Engineering'), ('EEE', 'Electrical and Electronics Engineering')], max_length=10)),
                ('section', models.CharField(choices=[('A', 'A Section'), ('B', 'B Section'), ('C', 'C Section')], max_length=1)),
                ('images', models.FileField(max_length=50, upload_to='ThirdYear')),
            ],
        ),
        migrations.DeleteModel(
            name='firstSemester',
        ),
    ]
