# Generated by Django 3.1.1 on 2020-10-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0006_auto_20201029_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstyear',
            options={'verbose_name_plural': 'First Year'},
        ),
        migrations.AlterModelOptions(
            name='fourthyear',
            options={'verbose_name_plural': 'Fourth Year'},
        ),
        migrations.AlterModelOptions(
            name='secondyear',
            options={'verbose_name_plural': 'Second Year'},
        ),
        migrations.AlterModelOptions(
            name='thirdyear',
            options={'verbose_name_plural': 'Third Year'},
        ),
        migrations.AlterField(
            model_name='firstyear',
            name='images',
            field=models.FileField(max_length=50, upload_to='CSE/FirstYear'),
        ),
        migrations.AlterField(
            model_name='fourthyear',
            name='images',
            field=models.FileField(max_length=50, upload_to='CSE/FourthYear'),
        ),
        migrations.AlterField(
            model_name='secondyear',
            name='images',
            field=models.FileField(max_length=50, upload_to='CSE/SecondYear'),
        ),
        migrations.AlterField(
            model_name='thirdyear',
            name='images',
            field=models.FileField(max_length=50, upload_to='CSE/ThirdYear'),
        ),
    ]
