# Generated by Django 3.2 on 2021-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0007_auto_20201029_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourthyear',
            name='usn',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
