# Generated by Django 3.2 on 2021-07-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0008_alter_fourthyear_usn'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourthYearASec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usn', models.CharField(max_length=10, unique=True)),
                ('date1', models.CharField(blank=True, max_length=1)),
                ('date2', models.CharField(blank=True, max_length=1)),
                ('date3', models.CharField(blank=True, max_length=1)),
                ('date4', models.CharField(blank=True, max_length=1)),
                ('date5', models.CharField(blank=True, max_length=1)),
                ('date6', models.CharField(blank=True, max_length=1)),
                ('date7', models.CharField(blank=True, max_length=1)),
                ('date8', models.CharField(blank=True, max_length=1)),
                ('date9', models.CharField(blank=True, max_length=1)),
                ('date10', models.CharField(blank=True, max_length=1)),
                ('date12', models.CharField(blank=True, max_length=1)),
                ('date13', models.CharField(blank=True, max_length=1)),
                ('date14', models.CharField(blank=True, max_length=1)),
                ('date15', models.CharField(blank=True, max_length=1)),
                ('date16', models.CharField(blank=True, max_length=1)),
                ('date17', models.CharField(blank=True, max_length=1)),
                ('date18', models.CharField(blank=True, max_length=1)),
                ('date19', models.CharField(blank=True, max_length=1)),
                ('date20', models.CharField(blank=True, max_length=1)),
                ('date21', models.CharField(blank=True, max_length=1)),
                ('date22', models.CharField(blank=True, max_length=1)),
                ('date23', models.CharField(blank=True, max_length=1)),
                ('date24', models.CharField(blank=True, max_length=1)),
                ('date25', models.CharField(blank=True, max_length=1)),
                ('date26', models.CharField(blank=True, max_length=1)),
                ('date27', models.CharField(blank=True, max_length=1)),
                ('date28', models.CharField(blank=True, max_length=1)),
                ('date29', models.CharField(blank=True, max_length=1)),
                ('date30', models.CharField(blank=True, max_length=1)),
                ('date31', models.CharField(blank=True, max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Fourth Year A Section',
            },
        ),
        migrations.DeleteModel(
            name='FirstYear',
        ),
        migrations.DeleteModel(
            name='FourthYear',
        ),
        migrations.DeleteModel(
            name='SecondYear',
        ),
        migrations.DeleteModel(
            name='ThirdYear',
        ),
    ]
