# Generated by Django 3.2 on 2021-08-08 15:16

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0010_auto_20210711_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourthyearasec',
            name='edate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fourthyearasec',
            name='ldate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 8, 15, 16, 21, 809474, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
