# Generated by Django 3.2 on 2021-08-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0011_auto_20210808_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fourthyearasec',
            old_name='edate',
            new_name='etime',
        ),
        migrations.RenameField(
            model_name='fourthyearasec',
            old_name='ldate',
            new_name='ltime',
        ),
    ]
