# Generated by Django 3.1.1 on 2020-10-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsAttendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameranumbers',
            options={'verbose_name_plural': 'Camara Details'},
        ),
        migrations.AddField(
            model_name='cameranumbers',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science Engineering'), ('ISE', 'Information Science Engineering'), ('ECE', 'Electronic Engineering'), ('ME', 'Mechanical Engineering'), ('CVE', 'Civil Engineering'), ('AI & ML', 'Artificial Intelligence and Machine Learning.'), ('TCE', 'Telecommunications Engineering'), ('EEE', 'Electrical and Electronics Engineering')], max_length=10),
        ),
        migrations.AddField(
            model_name='cameranumbers',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Third Semester'), ('4', 'Fourth Semester'), ('5', 'Fifth Semester'), ('6', 'Sixth Semester'), ('7', 'Seventh Semester'), ('8', 'Eighth Semester')], max_length=1),
        ),
        migrations.AddField(
            model_name='cameranumbers',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Third Semester'), ('4', 'Fourth Semester'), ('5', 'Fifth Semester'), ('6', 'Sixth Semester'), ('7', 'Seventh Semester'), ('8', 'Eighth Semester')], max_length=1),
        ),
    ]
