# Generated by Django 3.2 on 2021-07-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsAttendence', '0003_auto_20201029_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(blank=True, choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Third Semester'), ('4', 'Fourth Semester'), ('5', 'Fifth Semester'), ('6', 'Sixth Semester'), ('7', 'Seventh Semester'), ('8', 'Eighth Semester')], max_length=1)),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'Computer Science Engineering'), ('ISE', 'Information Science Engineering'), ('ECE', 'Electronic Engineering'), ('ME', 'Mechanical Engineering'), ('CVE', 'Civil Engineering'), ('AI & ML', 'Artificial Intelligence and Machine Learning.'), ('TCE', 'Telecommunications Engineering'), ('EEE', 'Electrical and Electronics Engineering')], max_length=10)),
                ('year', models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1)),
                ('section', models.CharField(blank=True, choices=[('A', 'A Section'), ('B', 'B Section'), ('C', 'C Section')], max_length=1)),
                ('image', models.ImageField(blank=True, upload_to='uploads')),
            ],
        ),
    ]
