# Generated by Django 3.2 on 2021-07-11 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studentsAttendence', '0004_studentsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdetails',
            name='usn',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
